TiXmlAttributeSet Class Reference
#include <tinyxml.h>
Detailed Description
A class used to manage a group of attributes. It is only used internally, both by the ELEMENT and the DECLARATION.
The set can be changed transparent to the Element and Declaration classes that use it, but NOT transparent to the Attribute which has to implement a next() and previous() method. Which makes it a bit problematic and prevents the use of STL.
This version is implemented with circular lists because:
I like circular lists
it demonstrates some independence from the (typical) doubly linked list.
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *attribute)
void Remove (TiXmlAttribute *attribute)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
const TiXmlAttribute * Find (const char *_name) const
TiXmlAttribute * Find (const char *_name)
Constructor & Destructor Documentation
TiXmlAttributeSet::TiXmlAttributeSet ()
References TiXmlAttribute::next, and TiXmlAttribute::prev.
TiXmlAttributeSet::~TiXmlAttributeSet ()
References TiXmlAttribute::next, and TiXmlAttribute::prev.
Member Function Documentation
void TiXmlAttributeSet::Add (TiXmlAttribute * attribute)
References Find(), TiXmlAttribute::Name(), TiXmlAttribute::next, TiXmlAttribute::prev, and TIXML_STRING.
Referenced by TiXmlElement::Parse(), and TiXmlElement::SetAttribute().
void TiXmlAttributeSet::Remove (TiXmlAttribute * attribute)
References TiXmlAttribute::next, and TiXmlAttribute::prev.
Referenced by TiXmlElement::ClearThis(), and TiXmlElement::RemoveAttribute().
const TiXmlAttribute* TiXmlAttributeSet::First () const [inline]
References TiXmlAttribute::next.
Referenced by TiXmlElement::Accept(), TiXmlElement::ClearThis(), TiXmlElement::CopyTo(), TiXmlElement::FirstAttribute(), and TiXmlElement::Print().
TiXmlAttribute* TiXmlAttributeSet::First () [inline]
References TiXmlAttribute::next.
const TiXmlAttribute* TiXmlAttributeSet::Last () const [inline]
References TiXmlAttribute::prev.
Referenced by TiXmlElement::LastAttribute().
TiXmlAttribute* TiXmlAttributeSet::Last () [inline]
References TiXmlAttribute::prev.
const TiXmlAttribute * TiXmlAttributeSet::Find (const char * _name) const
References TiXmlNode::next, and TiXmlAttribute::next.
Referenced by Add(), TiXmlElement::Attribute(), TiXmlElement::Parse(), TiXmlElement::QueryDoubleAttribute(), TiXmlElement::QueryIntAttribute(), TiXmlElement::RemoveAttribute(), and TiXmlElement::SetAttribute().
TiXmlAttribute* TiXmlAttributeSet::Find (const char * _name) [inline]
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp