Dummy::DummyMessageGenerator Class Reference
#include <dummymessagegenerator.hh>
Detailed Description
this class implements the messagegenerator
Todo
Author: Garrit Jentsch
Date: Oct 15, 2009 last edited 10-15-2009
Public Member Functions
DummyMessageGenerator ()
DummyMessageGenerator (Agent *)
~DummyMessageGenerator ()
void placeMessage ()
Constructor & Destructor Documentation
DummyMessageGenerator::DummyMessageGenerator ()
DummyMessageGenerator::DummyMessageGenerator (Agent * ag)
DummyMessageGenerator::~DummyMessageGenerator ()
Member Function Documentation
void DummyMessageGenerator::placeMessage () [virtual]
generate message and puts it into the outbox of the source agent
Implements Hive::MessageGenerator .
References Hive::Agent::placeMessageOnMessageQueue(), Hive::Message::setAction(), Hive::Message::setArgument(), and Hive::MessageGenerator::source.
The documentation for this class was generated from the following files:
dummymessagegenerator.hh
dummymessagegenerator.cpp