DummyWaveAction Class Reference
#include <dummywaveaction.hh>
Detailed Description
this is a dummy implementation of the action class
a dummywaveaction prints out 'wave' on cerr and adds the number of waves to the agents database item ...
Todo error-checking whether the counter exists in the agent
Author: garrit jentsch
Date: Oct 14, 2009 last edited 10-15-2009 by garrit
Public Member Functions
DummyWaveAction ()
DummyWaveAction (int id)
void fire (Data *d)
Constructor & Destructor Documentation
DummyWaveAction::DummyWaveAction ()
DummyWaveAction::DummyWaveAction (int id)
Member Function Documentation
void DummyWaveAction::fire (Data * d) [virtual]
executes an action
Parameters:
d pointer to data-object containing the argument for the action
Implements Action .
References Action::agent, Agent::getDatabase(), Database::getDataItem(), IntegerData::getInteger(), and Data::getType().
Referenced by DummyComposer::createAgent().
The documentation for this class was generated from the following files:
dummywaveaction.hh
dummywaveaction.cpp