hive.cpp File Reference
Detailed Description
The main entry point for hive.
This file contains the main function and some other things.
Author: Michael Sneddon
Date: Started: Oct 7, 2009 Last edited: Oct 14, 2009 by Michael and Garrit
Todo Fill in the details.
#include <iostream>
#include <string>
#include <time.h>
#include `agent/agent.hh`
#include `projects/dummyAgent/dummycomposer.hh`
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Main method for hive.
Parameters:
argc number of arguments (this is the length of argv)
argv[] pointer to char arrays (strings) that were passed as arguments
Returns: zero if hive ran successfully, an error code if it did not
References Hive::Composer::getTopLevelAgent(), Hive::Agent::propagate(), and Hive::Composer::setupSimulation().