Hive::Database Class Reference
#include <database.hh>
Detailed Description
Database of an agent.
The database of the agent class stores all of the agent's data. This is the most radical way for a generic database in that a database is a vector of void pointers.
Todo Implementation
Date: Started: Oct 7th, 2009 Last edited: Oct 14th, 2009 by Garrit and Michael
Public Member Functions
Database ()
Constructor.
~Database ()
Destructor.
void setup ()
void dumpDataBase (OutputWriter *ow)
void addData (string name, Data *data)
void eraseDataItem (string name)
Data * getDataItem (string name)
void readDataBase (InputDataReader *ir)
void returnPointerToData (string name, Data *&ptr)
bool existsDataItem (string name)
Protected Attributes
vector< Data * > real_database
the database is really nothing else but a vector of pointers to data objects
map< string, int > data_position_identifyer
map to give a name to the data items stored in the database
Constructor & Destructor Documentation
Database::Database ()
Constructor.
Database::~Database ()
Destructor.
Member Function Documentation
void Database::setup ()
outputs the entire database
Parameters:
ow Pointer to the OutputWriter that outputs the database
void Database::dumpDataBase (OutputWriter * ow)
outputs the entire database
Parameters:
ow Pointer to the OutputWriter that outputs the database
References real_database.
void Database::addData (string name, Data * data)
adds data to the database
Parameters:
name Name of the variable to be added
ptr Pointer to the data to be added
References data_position_identifyer, and real_database.
Referenced by Dummy::DummyAgentFactory::createAgent(), and Hive::DummySimulator::DummySimulator().
void Database::eraseDataItem (string name)
removes data item form the database
Parameters:
name Name of data item to be removed.
Data * Database::getDataItem (string name)
returns a data item
Parameters:
name identifyer of data item
Returns: pointer to data item
References data_position_identifyer, and real_database.
Referenced by Dummy::DummyWaveAction::fire(), Hive::DummySimulator::step(), and Hive::DummySimulator::synchroniseWithDatabase().
void Database::readDataBase (InputDataReader * ir)
set up a database by using an input reader
Parameters:
ir Pointer to an InputReader
void Database::returnPointerToData (string name, Data *& ptr)
returns pointer to data item
Parameters:
name Name of variable that one wishes to obtain a pointer to.
ptr Pointer to the desired variable.
References data_position_identifyer, and real_database.
bool Database::existsDataItem (string name)
ask for existence of a data_item
Parameters:
name name of dataitem
Returns: existence
References data_position_identifyer.
Member Data Documentation
vector<Data *> Hive::Database::real_database [protected]
the database is really nothing else but a vector of pointers to data objects
Referenced by addData(), dumpDataBase(), getDataItem(), and returnPointerToData().
map<string, int> Hive::Database::data_position_identifyer [protected]
map to give a name to the data items stored in the database
Referenced by addData(), existsDataItem(), getDataItem(), and returnPointerToData().
The documentation for this class was generated from the following files:
database.hh
database.cpp