Dummy::DummyComposer Class Reference
#include <dummycomposer.hh>
Public Member Functions
DummyComposer ()
~DummyComposer ()
void setupSimulation ()
Protected Member Functions
void initializeAgentFactories ()
void setupAgentHierarchy ()
Agent * getTopLevelAgent ()
Agent * createAgent (AgentFactory &)
Constructor & Destructor Documentation
DummyComposer::DummyComposer ()
DummyComposer::~DummyComposer ()
Member Function Documentation
void DummyComposer::setupSimulation () [virtual]
top level method for constructing the simulation. for the beginning we will re-implement this method for each new simulation
Implements Hive::Composer .
References createAgent(), Hive::Composer::factories, initializeAgentFactories(), Hive::Composer::maestro, Hive::Composer::orchestra, and setupAgentHierarchy().
void DummyComposer::initializeAgentFactories () [protected, virtual]
prepare agent factories for agent setup
Implements Hive::Composer .
References Hive::Composer::factories.
Referenced by setupSimulation().
void DummyComposer::setupAgentHierarchy () [protected, virtual]
establishes child parent relationships among agents
Implements Hive::Composer .
References Hive::SerialCommunicator::addAgent(), and Hive::Composer::orchestra.
Referenced by setupSimulation().
Agent * DummyComposer::getTopLevelAgent () [protected]
returns pointer to the top level agent
Returns: maestro
Reimplemented from Hive::Composer .
References Hive::Composer::maestro.
Agent * DummyComposer::createAgent (AgentFactory & af) [protected, virtual]
creates an agent
Parameters:
af agentfactory that does the actual creation of agents.
Returns: pointer to created agent
Implements Hive::Composer .
References Hive::AgentFactory::createAgent().
Referenced by setupSimulation().
The documentation for this class was generated from the following files:
dummycomposer.hh
dummyComposer.cpp