Hive::Message Class Reference
#include <message.hh>
Detailed Description
message for agent communication.
messages are exchanged by agents to communicate with one another. with the help of a message agents tell each other which action they should take.
See also: action
Todo everything. how do we specify the parameters ?!
Bug
Author: Garrit Jentsch
Date: Oct 13th, 2009 last edited: 10-14-2009 by Garrit and Michael
Public Member Functions
Message ()
Constructor.
~Message ()
destructor
int getActionId ()
void setAction (int a)
void setArgument (Data &d)
void setArgument (Data *d)
void getArgument (Data *&d, int i=0)
void getAllParameter (vector< Data * > &d)
Constructor & Destructor Documentation
Message::Message ()
Constructor.
Message::~Message ()
destructor
Member Function Documentation
int Message::getActionId ()
returns actionid of the action to be taken by the destination agent
Returns: actionid
Referenced by Hive::Agent::evaluateMessageQueue().
void Message::setAction (int a)
set action which has to be communicated
Parameters:
a action to be broadcasted.
Referenced by Dummy::DummyMessageGenerator::placeMessage().
void Hive::Message::setArgument (Data & d)
adds an arbitrary data item to the parameter list
Parameters:
d data item
Referenced by Dummy::DummyMessageGenerator::placeMessage().
void Message::setArgument (Data * d)
adds a pointer to an arbitrary data item to the parameter list
Parameters:
*d pointer to data item
void Message::getArgument (Data *& d, int i = 0)
return data item at a certain position
Parameters:
*d return parameter
i position
Referenced by Hive::Agent::evaluateMessageQueue().
void Hive::Message::getAllParameter (vector< Data * > & d)
return data item vector
Parameters:
**d return parameter
The documentation for this class was generated from the following files:
message.hh
message.cpp