TiXmlParsingData Class Reference
Public Member Functions
void Stamp (const char *now, TiXmlEncoding encoding)
const TiXmlCursor & Cursor ()
Friends
class TiXmlDocument
Member Function Documentation
void TiXmlParsingData::Stamp (const char * now, TiXmlEncoding encoding)
References TiXmlCursor::col, TiXmlCursor::row, TIXML_ENCODING_UTF8, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, and TiXmlBase::utf8ByteTable.
Referenced by TiXmlDeclaration::Parse(), TiXmlText::Parse(), TiXmlAttribute::Parse(), TiXmlComment::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Parse(), and TiXmlDocument::SetError().
const TiXmlCursor& TiXmlParsingData::Cursor () [inline]
Referenced by TiXmlDeclaration::Parse(), TiXmlText::Parse(), TiXmlAttribute::Parse(), TiXmlComment::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Parse(), TiXmlDocument::Parse(), and TiXmlDocument::SetError().
Friends And Related Function Documentation
friend class TiXmlDocument [friend]
The documentation for this class was generated from the following file:
tinyxmlparser.cpp