mu::ParserInt Class Reference
#include <muParserInt.h>
Detailed Description
Mathematical expressions parser.
This version of the parser handles only integer numbers. It disables the built in operators thus it is slower than muParser. Integer values are stored in the double value_type and converted if needed.
Public Member Functions
ParserInt ()
Constructor.
virtual void InitFun ()
Initialize the default functions.
virtual void InitOprt ()
Initialize operators.
virtual void InitConst ()
virtual void InitCharSets ()
Constructor & Destructor Documentation
mu::ParserInt::ParserInt ()
Constructor.
Call ParserBase class constructor and trigger Function, Operator and Constant initialization.
References mu::ParserBase::AddValIdent(), InitCharSets(), InitFun(), and InitOprt().
Member Function Documentation
void mu::ParserInt::InitFun () [virtual]
Initialize the default functions.
Implements mu::ParserBase .
Referenced by ParserInt().
void mu::ParserInt::InitOprt () [virtual]
Initialize operators.
Implements mu::ParserBase .
References mu::ParserBase::DefineInfixOprt(), mu::ParserBase::DefineOprt(), mu::ParserBase::EnableBuiltInOprt(), mu::prADD_SUB, mu::prCMP, mu::prLOGIC, and mu::prMUL_DIV.
Referenced by ParserInt().
void mu::ParserInt::InitConst () [virtual]
Implements mu::ParserBase .
void mu::ParserInt::InitCharSets () [virtual]
Implements mu::ParserBase .
References mu::ParserBase::DefineInfixOprtChars(), mu::ParserBase::DefineNameChars(), and mu::ParserBase::DefineOprtChars().
Referenced by ParserInt().
The documentation for this class was generated from the following files:
muParserInt.h
muParserInt.cpp