Util Namespace Reference
Detailed Description
General utility function library.
The set of functions included in the Util namespace inculdes a random number generator, constants that are often used, function and xml parsing libraries, conversions between primitive types, and other uncategorized utilites.
Author: Michael Sneddon
Functions
double convertToDouble (const std::string &s)
Parses and converts std::string objects to double values.
int convertToInt (const std::string &s)
Parses and converts std::string objects to int values.
string toString (double x)
Converts double values to their string representations.
string toString (int x)
Converts integer values to their string representations.
double RANDOM (double max)
Uniform random number on the interval (0,max].
double RANDOM_CLOSED ()
Uniform random number on the interval (0,1).
double RANDOM_GAUSSIAN ()
Normally distributed random number with mean 0 and variance 1.
int RANDOM_INT (unsigned long min, unsigned long max)
Uniform random number on the interval [min,max].
void SEED_RANDOM (unsigned long seed)
Seeds the random number generator used in all simulations.
void trim (std::string &str)
Removes leading and trailing whitespace (including tabs) from the string.
Variables
const double PI = 3.141592653589793
The value of Pi up to 16 significant digits.
const double NA = 6.02214179e23
The value of Avogadro's Number up to 9 significant digits.
Function Documentation
double Util::convertToDouble (const std::string & s)
Parses and converts std::string objects to double values.
Just uses the standard library operations for converting strings to double values. Throws a run time exception if the parse failed.
Parameters:
s the string to act on
Author: Michael Sneddon
Referenced by Hive::parseAsDouble().
int Util::convertToInt (const std::string & s)
Parses and converts std::string objects to int values.
Just uses the standard library operations for converting strings to integers. Throws a run time exception if the parse failed.
Parameters:
s the string to act on
Author: Michael Sneddon
Referenced by Hive::parseAsInt().
double Util::RANDOM (double max)
Uniform random number on the interval (0,max].
This function returns a random double on the half open interval (0,max]
Parameters:
max the max value that can be generated, inclusive
Returns: double the random deviate
Author: Michael Sneddon
References dRand, initflag, and MTRand_int32::seed().
double Util::RANDOM_CLOSED ()
Uniform random number on the interval (0,1).
This function returns a random double on the closed interval (0,1)
Returns: double the random deviate
Author: Michael Sneddon
References dRandClosed, initflag, and MTRand_int32::seed().
Referenced by Hive::DummySimulator::step().
double Util::RANDOM_GAUSSIAN ()
Normally distributed random number with mean 0 and variance 1.
Returns a normally distributed random number. Based on the java implementation of Random.nextGaussian, this method uses the polar method of G. E. P. Box, M. E. Muller, and G. Marsaglia, as described by Donald E. Knuth in The Art of Computer Programming, Volume 2: Seminumerical Algorithms, section 3.4.1, subsection C, algorithm P.
Returns: double normally distributed random number
Author: Michael Sneddon
References dRandOpen, haveNextGaussian, initflag, nextGaussian, and MTRand_int32::seed().
int Util::RANDOM_INT (unsigned long min, unsigned long max)
Uniform random number on the interval [min,max].
This is a multipurpose function that selects a random number on the half open interval [min, max). This allows you to quickly select a random element from a list of known size. The function call would look something like: RANDOM_INT(0,sizeOfList).
Parameters:
min the minimum number that can be generated, inclusive
max the maximum number that can be generated, exclusive
Returns: int the random integer
Author: Michael Sneddon
References dRand, initflag, and MTRand_int32::seed().
void Util::SEED_RANDOM (unsigned long seed)
Seeds the random number generator used in all simulations.
Seed the random number generator with a positive 32bit integer If you don't call this function, the current time will be used as a seed so each run will be different.
Parameters:
seed the number to seed the random generator
Author: Michael Sneddon
References initflag, and MTRand_int32::seed().
std::string Util::toString (int x)
Converts integer values to their string representations.
Parameters:
x the integer number to act on
Author: Michael Sneddon
std::string Util::toString (double x)
Converts double values to their string representations.
Parameters:
x the double number to act on
Author: Michael Sneddon
void Util::trim (std::string & str)
Removes leading and trailing whitespace (including tabs) from the string.
Note that this function takes arguements by reference, so that it trims the string you give it. If you want to trim a copy of your string, you will have to make the copy yourself.
Parameters:
str the string to act on (pass by reference)
Author: Michael Sneddon
Variable Documentation
const double Util::NA = 6.02214179e23
The value of Avogadro's Number up to 9 significant digits.
Author: Michael Sneddon
const double Util::PI = 3.141592653589793
The value of Pi up to 16 significant digits.
Author: Michael Sneddon