tinystr.cpp File Reference
#include `tinystr.h`
Functions
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
Function Documentation
TiXmlString operator+ (const char * a, const TiXmlString & b)
References TiXmlString::append(), TiXmlString::length(), and TiXmlString::reserve().
TiXmlString operator+ (const TiXmlString & a, const char * b)
References TiXmlString::append(), TiXmlString::length(), and TiXmlString::reserve().
TiXmlString operator+ (const TiXmlString & a, const TiXmlString & b)
References TiXmlString::length(), and TiXmlString::reserve().