Hive::Agent Class Reference
#include <agent.hh>
Detailed Description
central class of the hive
the agent is the central class of the hive. an agent contains a database in which it stores its knowledge. its simulators operate on the data stored within the database. communication among agents is accomplished with the communicator. when agents communicate they place messages on to the message queue of another agent. a message tells the agent to perform an action from its actionset.
Todo Everything
Bug
Author: Garrit Jentsch
Date: Oct 12th, 2009 last edited: Oct 14h, 2009 by Garrit and Michael
Public Member Functions
Agent ()
constructor
Agent (int agent_id)
~Agent ()
destructor
void setParent (int parent_id)
void addChild (int child_id)
void addAction (Action *a)
void addCommunicator (Communicator *c)
void addMessageGenerator (MessageGenerator *msg)
void addSimulator (Simulator *s)
Database * getDatabase ()
int getParentId ()
int getAgentId ()
int getNumOfChildren ()
int getChildAgentId (int childIndex)
bool isChildAgent (int agentId)
void outputCurrentState (OutputWriter *ow)
void placeMessageOnMessageQueue (Message *m)
void propagate (double time)
propagates the agent for a timestep
void setupDatabase ()
Protected Member Functions
void evaluateMessageQueue ()
causes the agent to perform the actions placed on the message queue.
Protected Attributes
int agent_id
unique identifyer of this agent
int parent_id
unique identifyer of the parent agent
vector< int > children_id
unique identifyers of the child agents
Database * db
database of the agent
Communicator * c
communicator for exchanging messages with the agent's parent agent andchildren
queue< Message * > message_queue
message queue; inbox of an agent
vector< Simulator * > simulators
vector of simulators
vector< Action * > action_set
actionset. a message tells the agent to execute an action from this set
vector< Message * > outbox
message outbox of agent.
vector< MessageGenerator * > message_generators
vector of pointers to message_generators
Constructor & Destructor Documentation
Agent::Agent ()
constructor
unique identifyer of this agent
database of the agent
communicator for exchanging messages with the agent's parent agent andchildren
message queue; inbox of an agent
vector of simulators
actionset. a message tells the agent to execute an action from this set
message outbox of agent.
vector of pointers to message_generators
References agent_id, db, and parent_id.
Agent::Agent (int agent_id)
References db.
Agent::~Agent ()
destructor
References agent_id.
Member Function Documentation
void Agent::setParent (int parent_id)
set the parent of this agent
Parameters:
parent_id id of the parent
void Agent::addChild (int child_id)
add a child of this agent
Parameters:
child_id id of child to add
References children_id.
void Agent::addAction (Action * a)
adds an action to the actionset
Parameters:
a action to be added to actionset
References action_set.
Referenced by Dummy::DummyAgentFactory::createAgent().
void Agent::addCommunicator (Communicator * c)
adds communicator to the system
Parameters:
c communicator to be added
void Agent::addMessageGenerator (MessageGenerator * msg)
adds a message generator to the agent
Parameters:
msg messagegenerator
References message_generators.
Referenced by Dummy::DummyAgentFactory::createAgent().
void Agent::addSimulator (Simulator * s)
adds a simulator to the simulators vector
Parameters:
s simulator to be added
References simulators.
Referenced by Dummy::DummyAgentFactory::createAgent().
Hive::Database * Agent::getDatabase ()
method for accessing database of an agent
Returns: pointer to database
References db.
Referenced by Dummy::DummyAgentFactory::createAgent(), Hive::DummySimulator::DummySimulator(), and Dummy::DummyWaveAction::fire().
int Agent::getParentId ()
return parent agent ID
Returns: ID of the parent agent
References parent_id.
int Agent::getAgentId ()
return this agent ID
Returns: ID of the parent agent
References agent_id.
Referenced by Hive::SerialCommunicator::addAgent(), Hive::DummySimulator::prepare(), and Hive::DummySimulator::synchroniseWithDatabase().
int Agent::getNumOfChildren ()
get the number of child agents
Returns: the number of children
References children_id.
int Agent::getChildAgentId (int childIndex)
return the ID of the child agent at the given index
Parameters:
childIndex index of the child agent ID to return
References children_id.
bool Agent::isChildAgent (int agentId)
check if the given ID is a child of this
Returns: true if the agentID given is a child, false otherwise childIndex index of the child agent ID to return
References children_id.
void Agent::outputCurrentState (OutputWriter * ow)
outputs the current state of the agent by dumbing its database
Parameters:
ow pointer to outputwriter who does the actual job
References agent_id.
void Hive::Agent::placeMessageOnMessageQueue (Message * m) [inline]
References message_queue.
Referenced by Dummy::DummyMessageGenerator::placeMessage().
void Agent::propagate (double time)
propagates the agent for a timestep
References agent_id, c, children_id, evaluateMessageQueue(), message_generators, outbox, Hive::Communicator::propogateAgent(), Hive::Communicator::sendMessage(), and simulators.
Referenced by main().
void Agent::setupDatabase ()
method for initializing the database. again the actual job is being done by the database-initializer
Parameters:
*db_init pointer to database initializer
References agent_id.
void Agent::evaluateMessageQueue () [protected]
causes the agent to perform the actions placed on the message queue.
References action_set, agent_id, Hive::Message::getActionId(), Hive::Message::getArgument(), and message_queue.
Referenced by propagate().
Member Data Documentation
int Hive::Agent::agent_id [protected]
unique identifyer of this agent
Referenced by Agent(), evaluateMessageQueue(), getAgentId(), outputCurrentState(), propagate(), setupDatabase(), and ~Agent().
int Hive::Agent::parent_id [protected]
unique identifyer of the parent agent
Referenced by Agent(), and getParentId().
vector<int> Hive::Agent::children_id [protected]
unique identifyers of the child agents
Referenced by addChild(), getChildAgentId(), getNumOfChildren(), isChildAgent(), and propagate().
Database* Hive::Agent::db [protected]
database of the agent
Referenced by Agent(), and getDatabase().
Communicator* Hive::Agent::c [protected]
communicator for exchanging messages with the agent's parent agent andchildren
Referenced by propagate().
queue<Message* > Hive::Agent::message_queue [protected]
message queue; inbox of an agent
Referenced by evaluateMessageQueue(), and placeMessageOnMessageQueue().
vector<Simulator *> Hive::Agent::simulators [protected]
vector of simulators
Referenced by addSimulator(), and propagate().
vector<Action *> Hive::Agent::action_set [protected]
actionset. a message tells the agent to execute an action from this set
Referenced by addAction(), and evaluateMessageQueue().
vector<Message *> Hive::Agent::outbox [protected]
message outbox of agent.
Referenced by propagate().
vector<MessageGenerator* > Hive::Agent::message_generators [protected]
vector of pointers to message_generators
Referenced by addMessageGenerator(), and propagate().
The documentation for this class was generated from the following files:
agent.hh
agent.cpp