Dummy::DummyAgentFactory Class Reference
#include <dummyagentfactory.hh>
Detailed Description
simple implementation of an agentfactory
this is a minimal implemtation of the agentfactory. it generates agents that can not really do anything.
Author: Garrit Jentsch
Date: Oct 14, 2009 last edited Oct 15, 2009
Public Member Functions
DummyAgentFactory ()
DummyAgentFactory (InputSystemReader *isr)
Agent * createAgent ()
Agent * createAgent (Action **ac)
Agent * duplicateAgent (Agent *ag)
Protected Member Functions
void addActionToAgentsActionSet (Action *a)
void addSimulatorToAgent (Simulator *s)
Constructor & Destructor Documentation
DummyAgentFactory::DummyAgentFactory ()
DummyAgentFactory::DummyAgentFactory (InputSystemReader * isr)
Member Function Documentation
Agent * DummyAgentFactory::createAgent () [virtual]
create agent of a certain type. encapsulates everything that has to be done, i.e. it adds actions, simulator, messagegenerators, and communicator to the agent. the simulator is also told to connect to the database and initialize itself.
Returns: pointer to constructed agent
Implements Hive::AgentFactory .
References Hive::Agent::addAction(), Hive::Database::addData(), Hive::Agent::addMessageGenerator(), Hive::Agent::addSimulator(), Hive::Agent::getDatabase(), Hive::IntegerData::getDataName(), and Hive::Action::setAgent().
Agent * DummyAgentFactory::createAgent (Action ** as) [virtual]
create an agent and provide actionset as an argument
Parameters:
as pointer to actionset
Implements Hive::AgentFactory .
Agent * DummyAgentFactory::duplicateAgent (Agent * ag) [virtual]
copies an agent
Parameters:
*ag pointer to agent to be copied
Returns: pointer to copy
Implements Hive::AgentFactory .
void DummyAgentFactory::addActionToAgentsActionSet (Action * a) [protected, virtual]
adds an action to the agents action set
Parameters:
*a pointer to action
Implements Hive::AgentFactory .
void DummyAgentFactory::addSimulatorToAgent (Simulator * s) [protected, virtual]
adds a simulator to the agents simulator set
Parameters:
*s pointer to simulator
Implements Hive::AgentFactory .
The documentation for this class was generated from the following files:
dummyagentfactory.hh
dummyagentfactory.cpp