Hive::DummySimulator Class Reference
#include <dummySimulator.hh>
Public Member Functions
DummySimulator (Agent *a)
Constructor.
~DummySimulator ()
destructor
void step (double t)
void prepare ()
void synchroniseWithDatabase ()
Protected Member Functions
void initialise ()
Constructor & Destructor Documentation
DummySimulator::DummySimulator (Agent * a)
Constructor.
References Hive::Database::addData(), Hive::Simulator::agent, and Hive::Agent::getDatabase().
DummySimulator::~DummySimulator ()
destructor
Member Function Documentation
void DummySimulator::step (double t) [virtual]
integrate the system for a timestep
Parameters:
t timestep
Implements Hive::Simulator .
References Hive::Database::getDataItem(), Util::RANDOM_CLOSED(), and Hive::DoubleData::setDouble().
void DummySimulator::prepare () [virtual]
prepare simulator for the first time, this will call the connectToDataBase and initialise methods
Implements Hive::Simulator .
References Hive::Simulator::agent, and Hive::Agent::getAgentId().
void DummySimulator::synchroniseWithDatabase () [virtual]
update simulator's internal variables before executing the integrate command
Implements Hive::Simulator .
References Hive::Simulator::agent, Hive::Agent::getAgentId(), Hive::Database::getDataItem(), and Hive::DoubleData::getDouble().
void DummySimulator::initialise () [protected, virtual]
initialise simulator's internal variables for the first time
Implements Hive::Simulator .
The documentation for this class was generated from the following files:
dummySimulator.hh
dummySimulator.cpp