TiXmlString Class Reference
#include <tinystr.h>
Public Types
typedef size_t size_type
Public Member Functions
TiXmlString ()
TiXmlString (const TiXmlString &copy)
TIXML_EXPLICIT TiXmlString (const char *copy)
TIXML_EXPLICIT TiXmlString (const char *str, size_type len)
~TiXmlString ()
TiXmlString & operator= (const char *copy)
TiXmlString & operator= (const TiXmlString &copy)
TiXmlString & operator+= (const char *suffix)
TiXmlString & operator+= (char single)
TiXmlString & operator+= (const TiXmlString &suffix)
const char * c_str () const
const char * data () const
size_type length () const
size_type size () const
bool empty () const
size_type capacity () const
const char & at (size_type index) const
char & operator[] (size_type index) const
size_type find (char lookup) const
size_type find (char tofind, size_type offset) const
void clear ()
void reserve (size_type cap)
TiXmlString & assign (const char *str, size_type len)
TiXmlString & append (const char *str, size_type len)
void swap (TiXmlString &other)
Static Public Attributes
static const size_type npos = static_cast< TiXmlString::size_type >(-1)
Classes
struct Rep
Member Typedef Documentation
typedef size_t TiXmlString::size_type
Constructor & Destructor Documentation
TiXmlString::TiXmlString () [inline]
TiXmlString::TiXmlString (const TiXmlString & copy) [inline]
References data(), and length().
TIXML_EXPLICIT TiXmlString::TiXmlString (const char * copy) [inline]
References length().
TIXML_EXPLICIT TiXmlString::TiXmlString (const char * str, size_type len) [inline]
TiXmlString::~TiXmlString () [inline]
Member Function Documentation
TiXmlString& TiXmlString::operator= (const char * copy) [inline]
References assign().
TiXmlString& TiXmlString::operator= (const TiXmlString & copy) [inline]
References assign(), length(), and start().
TiXmlString& TiXmlString::operator+= (const char * suffix) [inline]
References append().
TiXmlString& TiXmlString::operator+= (char single) [inline]
References append().
TiXmlString& TiXmlString::operator+= (const TiXmlString & suffix) [inline]
References append(), data(), and length().
const char* TiXmlString::c_str () const [inline]
Referenced by find(), operator<(), and operator==().
const char* TiXmlString::data () const [inline]
Referenced by operator+=(), reserve(), and TiXmlString().
size_type TiXmlString::length () const [inline]
Referenced by append(), at(), find(), operator+(), operator+=(), operator=(), operator==(), operator[](), reserve(), and TiXmlString().
size_type TiXmlString::size () const [inline]
bool TiXmlString::empty () const [inline]
size_type TiXmlString::capacity () const [inline]
Referenced by append(), assign(), and reserve().
const char& TiXmlString::at (size_type index) const [inline]
References length().
]char& TiXmlString::operator[] (size_type index) const [inline]
References length().
size_type TiXmlString::find (char lookup) const [inline]
size_type TiXmlString::find (char tofind, size_type offset) const [inline]
References c_str(), length(), and npos.
void TiXmlString::clear () [inline]
void TiXmlString::reserve (size_type cap)
References capacity(), data(), init(), length(), start(), and swap().
Referenced by append(), and operator+().
TiXmlString & TiXmlString::assign (const char * str, size_type len)
References capacity(), init(), start(), and swap().
Referenced by operator=().
TiXmlString & TiXmlString::append (const char * str, size_type len)
References capacity(), length(), and reserve().
Referenced by operator+(), and operator+=().
void TiXmlString::swap (TiXmlString & other) [inline]
References rep_.
Referenced by assign(), and reserve().
Member Data Documentation
const TiXmlString::size_type TiXmlString::npos = static_cast< TiXmlString::size_type >(-1) [static]
Referenced by find().
The documentation for this class was generated from the following files:
tinystr.h
tinystr.cpp